### ISSUE TITLE
Add Minilibx

### ISSUE THREAD

**Issue by GQDeltex** [Eduard953/Cub3D#14]
Add the minilibx source to the project and add respective rules to the Makefile.
In the Makefile we have to do some checks to Compile stuff differently on different systems 
```Makefile
OS := $(shell uname -s | tr A-Z a-z)

ifeq ($(OS), linux)
    # Do the Linux stuff
endif
ifeq ($(OS), darwin)
    # Do the MacOS stuff
endif
```

For reference: https://harm-smits.github.io/42docs/libs/minilibx/getting_started.html

**Comment by GQDeltex** [comment]
Just added the [minilibx-linux](https://github.com/42Paris/minilibx-linux) from Codam (in the 42Paris repo) (ddd0d08). @Eduard953 can you test if this compiles on your machine? You might have to add the following to the main function temporarily:
```c
//...
void *mlx;

mlx = mlx_init();
mlx_new_window(mlx, 300, 300, "Cub3D");
mlx_loop(mlx);
//...
```
I can check compilation on the School Macs on Monday

**Comment by Eduard953** [comment]
Did you add the one from the paris repo or this [codam version](https://github.com/codam-coding-college/MLX42 
) as we can't use the second one.

**Comment by Eduard953** [comment]
This is the error I'm getting.

`ld: warning: directory not found for option '-L./libraries/mlx/binaries'
ld: library not found for -lXext
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [binaries/Cub3D] Error 1`

**Comment by GQDeltex** [comment]
> Did you add the one from the paris repo or this [codam version](https://github.com/codam-coding-college/MLX42) as we can't use the second one.

I added the one I linked. Well after visiting your link it seems like the Codam Version is a totally different one, didn't know that. But it is the Minilibx from 42Paris

**Comment by GQDeltex** [comment]
Minilibx now compiles on the school macs. I added the install instructions for all the required X11 tools to the README.md (8a30d27). @Eduard953  Can you maybe install all that and try compiling again?

**Comment by Eduard953** [comment]
It does compile now, but I get this warning:
`ld: warning: directory not found for option '-L./libraries/mlx/binaries'`

**Comment by GQDeltex** [comment]
Well I'd say a warning is not that big of a Problem. So I'd say it's done. Closing
